//Harshavardhan Khot
#include<iostream>
#include<cstdlib>
#include<ctime>
using namespace std;
int main()
{
    //this function is generate random number using the real time clock
    srand(time(0));
    int RNumber=rand()%100;
    int EnterNum,count=0;
    cout<<"WELLCOME TO THE NUMBER GUESS GAME !"<<endl;
    cout<<"I Chosen a number between 0 to 100 range can you Guess that Number !"<<endl;
    do
    {
        //this loop use is try to guess number
        //if the user enter wrong number and it will showing the enter number is greater or less than the enter number
        cout<<endl<<"Enter Guess Number:";
        cin>>EnterNum;
        count++;
        if(EnterNum==RNumber)
        {
            //this loop is execute when the enter number by the user and is equal to the
            //random number generated by the computer using time
            cout<<endl<<"Congratulation's ! You Win ! You Guessed Number in "<<count<<" attempts ";
            cout<<endl<<"The Number is :"<<EnterNum;
            break;
        }
        else if(EnterNum>RNumber)
        {
            cout<<endl<<"It's Too Higher Number ! Try Again!";
            //it will display when enterd number is Higher than Random Number
        }
        else{
            cout<<endl<<"It's Too Lower Number ! Try Again!";
            //it will display when enterd number is Lower than Random Number
        }
    }while(EnterNum!=RNumber);

return 0;
}